/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-01-10 02:41:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.main;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("      <script src='");
      out.print(request.getContextPath() );
      out.write("/js/login.js'></script>\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\n");
      out.write("    function openPop(){\n");
      out.write("        var pop_title = \"popupOpener\" ;\n");
      out.write("        var frmData = document.frm_search ;\n");
      out.write("        frmData.action = \"../product_list/select.jsp\" ;\n");
      out.write("        frmData.submit() ;\n");
      out.write("    }\n");


	String user_id = (String) session.getAttribute("member_mid");
	session.setAttribute("user_id", user_id);

      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<header id=\"header\">\n");
      out.write("      <nav class=\"left\">\n");
      out.write("   \n");
      out.write("           <div class=\"search_bar\">\n");
      out.write("                 <form  name=\"frm_search\" role=\"search\" method=\"get\" class=\"search-form\" >\n");
      out.write("                     <input type=\"search\" class=\"search-field\" placeholder=\"상품명\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.findStr }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"findStr\" />\n");
      out.write("                    <button type=\"submit\"  name=\"btnFind\" class=\"search-submit\" onClick=\"openPop();\">검색</button>\n");
      out.write("               <input type=\"hidden\" name=\"search\" value=\"select\">\n");
      out.write("                 </form>\n");
      out.write("            </div> \n");
      out.write("  \n");
      out.write("        </nav>\n");
      out.write("        <a href =\"");
      out.print(request.getContextPath() );
      out.write("/main/index.jsp\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/pineapple.png\"/></a>\n");
      out.write("      <nav class=\"right\">\n");
      out.write("         <div class = \"menubar\">\n");
      out.write("               <li>\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/intro/intro.jsp\" class=\"button alt\">소개</a>\n");
      out.write("                  <ul>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/intro/intro.jsp\" >회사소개</a>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/intro/vision.jsp\" >회사비전</a>\n");
      out.write("                  </ul>\n");
      out.write("               </li>\n");
      out.write("               <li>\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/notice.jsp\" class=\"button alt\">커뮤니티</a>\n");
      out.write("                  <ul>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/notice/notice.jsp\" >공지사항</a>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/event/event.jsp\" >이벤트</a>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/review.do?job=select\" >리뷰 게시판</a>\n");
      out.write("                  </ul>\n");
      out.write("               </li>\n");
      out.write("               <li>\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/inquiry.do?job=select\" class=\"button alt\">고객지원</a>\n");
      out.write("                  <ul>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/inquiry.do?job=select\">QnA게시판</a>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/faqbook.do?qa=selectFaq\">FAQ</a></br>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/cs_center/cs_func_page.jsp?func=../cs_center/cs_map.jsp\" >오시는 길</a>\n");
      out.write("                  </ul>\n");
      out.write("               </li>\n");
      out.write("               \n");
      out.write("              \n");
      out.write("               \n");
      out.write("              	");

				String admin = (String)session.getAttribute("adminOk");
				if(admin !=null){
				
      out.write(" \n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/admin_index.jsp\" class=\"button alt\">관리자</a></li>  \n");
      out.write("                <li><input type='button' id='btnLogout' value='로그아웃' /></li>         \n");
      out.write("               ");
}else if( session.getAttribute("member_mid")== null){ //mid의 속성이 없으면 로그인 이전화면
               
      out.write("            \n");
      out.write("               <li>\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/UsersJoin/agree.jsp\" class=\"button alt\">회원가입</a>     \n");
      out.write("               </li>\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/login/loginfo.jsp\" class=\"button alt\">로그인</a></li>  \n");
      out.write("               ");
} else {
      out.write("\n");
      out.write("                <li>\n");
      out.write("                  <a href=\"");
      out.print(request.getContextPath() );
      out.write("/mypage/mypage\" class=\"button alt\">마이룸</a>\n");
      out.write("                  <ul>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/mypage/cart.jsp\" >장바구니</a>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/mypage/orderlist.jsp\" >주문내역</a>\n");
      out.write("                     <a href=\"");
      out.print(request.getContextPath() );
      out.write("/mypage/coupon.jsp\" >쿠폰함</a>\n");
      out.write("                  </ul>\n");
      out.write("               </li>\n");
      out.write("                <li><input type='button' id='btnLogout' value='로그아웃' /></li>         \n");
      out.write("                ");
} 
      out.write("         \n");
      out.write("           </div>\n");
      out.write("        </nav>  \n");
      out.write("   </header>\n");
      out.write("   <script>logInOut()</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
