/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-01-09 10:21:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class main2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" , initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<title>임시 메인</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"wrap\">\r\n");
      out.write("      <div class=\"intro_bg\">\r\n");
      out.write("        <div class=\"header\" id=\"link_header\">\r\n");
      out.write("          <div class=\"searchArea\">\r\n");
      out.write("            <form>\r\n");
      out.write("              <input type=\"search\" placeholder=\"Search\" />\r\n");
      out.write("              <span>검색</span>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"nav\">\r\n");
      out.write("            <li><a href=\"#link_header\">홈페이지</a></li>\r\n");
      out.write("            <li><a href=\"#link_main_text0\">장바구니</a></li>\r\n");
      out.write("            <li><a href=\"#link_main_text1\">서비스</a></li>\r\n");
      out.write("            <li><a href=\"#link_main_text2\">CONTACT</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"intro_text\">\r\n");
      out.write("          <h1>총알 오징어, 세마리에 만원</h1>\r\n");
      out.write("          <h4 class=\"contents1\">\r\n");
      out.write("            우리는 전기를 이용해 실수인척 새끼 오징어를 불법 포획합니다\r\n");
      out.write("          </h4>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--intro end-->\r\n");
      out.write("      <ul class=\"amount\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"contents1\">총 주문수</div>\r\n");
      out.write("            <div class=\"result\">10000건</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"contents1\">진행중인 주문수</div>\r\n");
      out.write("            <div class=\"result\">5000건</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"contents1\">완료된 주문수</div>\r\n");
      out.write("            <div class=\"result\">3건</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"contents1\">목표 주문량</div>\r\n");
      out.write("            <div class=\"result\">100000000건</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <!-- amount end-->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"main_text0\" id=\"link_main_text0\">\r\n");
      out.write("        <h1>ABOUT</h1>\r\n");
      out.write("        <div class=\"contents1\">쇼핑몰 테스트 중 입니다</div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"icons\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <div class=\"icon_img\">\r\n");
      out.write("              <img src=\"image/icon2.svg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents1_bold\">신상품</div>\r\n");
      out.write("            <div class=\"contents2\">\r\n");
      out.write("              할 수 있다. 아마도 할 수 있다, 할 수 있을까?\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"more\">MORE</div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <div class=\"icon_img\">\r\n");
      out.write("              <img src=\"image/icon0.svg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents1_bold\">마이 페이지</div>\r\n");
      out.write("            <div class=\"contents2\">\r\n");
      out.write("              할 수 있다. 아마도 할 수 있다, 할 수 있을까?\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"more\">MORE</div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <div class=\"icon_img\">\r\n");
      out.write("              <img src=\"image/icon1.svg\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contents1_bold\">장바 구니</div>\r\n");
      out.write("            <div class=\"contents2\">\r\n");
      out.write("              할 수 있다. 아마도 할 수 있다, 할 수 있을까?\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"more\">MORE</div>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"main_text1\" id=\"link_main_text1\">\r\n");
      out.write("        <h1>SERVICE</h1>\r\n");
      out.write("        <div class=\"contents1\">엄격한 유통과정</div>\r\n");
      out.write("        <div class=\"service\">\r\n");
      out.write("          <div class=\"food_photo\">\r\n");
      out.write("            <img src=\"image/food.png\" />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"contents2\">\r\n");
      out.write("          <h2>이것이 오징어야, 문어야?</h2>\r\n");
      out.write("          이것이 오징어인지 문어인지 헷갈리시는 분들도 있을거에요.\r\n");
      out.write("          <br />왜냐하면 이것은 ?\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"main_text2\" id=\"link_main_text2\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>\r\n");
      out.write("            <div><h1>CONTACT</h1></div>\r\n");
      out.write("            <div>우리에게 파트너십을 신청하거나, 고객이 되어주세요</div>\r\n");
      out.write("            <div class=\"more2\">\r\n");
      out.write("              더 알아보기\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <footer>\r\n");
      out.write("        <div>\r\n");
      out.write("            LOGO\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("          CEO, 윤희재<br>\r\n");
      out.write("          Addr, 서울 특별시 관악구 신림동 ??\r\n");
      out.write("          010-2323-4567 <br>\r\n");
      out.write("          COPYRIGHT 2023, HEEJAE, ALL RIGHT RESERVED.\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
