/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-01-10 00:59:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import user.User;
import user.UserDAO;
import java.util.ArrayList;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/bottom.jsp", Long.valueOf(1672989562555L));
    _jspx_dependants.put("/top.jsp", Long.valueOf(1673312301643L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.User");
    _jspx_imports_classes.add("user.UserDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>마켓퀄리 회원가입</title>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!-- <meta name=\"viewport\" content=\"width=device-width\" , initial-scale=\"1\"> -->\r\n");
      out.write("<style>\r\n");
      out.write(".newloginhr {\r\n");
      out.write("	height: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".essencial {\r\n");
      out.write("	margin-left: 570px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".im {\r\n");
      out.write("	color: orange;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#text, #postcode, #detailaddress, #address {\r\n");
      out.write("	width: 350px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	border: 1px solid #e1e1e1;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#button {\r\n");
      out.write("	outline: none;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	border: 1px solid #8ca86e;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	color: #5d5d5d;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("	height: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(2), tr:nth-child(4), tr:nth-child(6), tr:nth-child(10) {\r\n");
      out.write("	height: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false\"></script>\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document)\r\n");
      out.write("				.ready(\r\n");
      out.write("						function() {\r\n");
      out.write("							$('input[name=\"userId\"]').focus();\r\n");
      out.write("\r\n");
      out.write("							$('input[name=\"userPw\"]').click(function() {\r\n");
      out.write("								$('.pwmsg').toggle(\"1000\");\r\n");
      out.write("\r\n");
      out.write("							});\r\n");
      out.write("							$('input[name=\"userRePw\"]').click(function() {\r\n");
      out.write("								$('.repwmsg').toggle(\"1000\");\r\n");
      out.write("							});\r\n");
      out.write("\r\n");
      out.write("							var use;\r\n");
      out.write("							var isCheck = false;\r\n");
      out.write("							var isChange = false;\r\n");
      out.write("							var isBlank = false;\r\n");
      out.write("\r\n");
      out.write("							$('input[name=\"userIdCheck\"]')\r\n");
      out.write("									.click(\r\n");
      out.write("											function() {\r\n");
      out.write("\r\n");
      out.write("												isCheck = true;\r\n");
      out.write("												isChange = false;\r\n");
      out.write("\r\n");
      out.write("												if ($('input[name=\"userId\"]')\r\n");
      out.write("														.val() == \"\") {\r\n");
      out.write("													alert(\"아이디를 입력하세요\");\r\n");
      out.write("													isBlank = true;\r\n");
      out.write("													return;\r\n");
      out.write("												}\r\n");
      out.write("\r\n");
      out.write("												isBlank = false;\r\n");
      out.write("\r\n");
      out.write("												$\r\n");
      out.write("														.ajax({ // 전체 새로고침이 아니라 화면의 일부만 바꿈(시간 절약)\r\n");
      out.write("															url : \"idcheck.jsp\", // 요청 url\r\n");
      out.write("															data : {\r\n");
      out.write("																id : $('.idch')\r\n");
      out.write("																		.val()\r\n");
      out.write("															},\r\n");
      out.write("															success : function(\r\n");
      out.write("																	data) { // 응답이 왔을 때. 변수data에 url이 들어감.\r\n");
      out.write("																/* alert(\"data: \"+$.trim(data)) */\r\n");
      out.write("																if ($\r\n");
      out.write("																		.trim(data) == \"no\") {\r\n");
      out.write("																	$(\r\n");
      out.write("																			'#message1')\r\n");
      out.write("																			.html(\r\n");
      out.write("																					\"<font color=red>이미 사용중인 아이디입니다.</font>\");\r\n");
      out.write("																	$(\r\n");
      out.write("																			'#message1')\r\n");
      out.write("																			.show();\r\n");
      out.write("																	use = \"impossible\";\r\n");
      out.write("																} else {\r\n");
      out.write("																	$(\r\n");
      out.write("																			'#message1')\r\n");
      out.write("																			.html(\r\n");
      out.write("																					\"<font color=green>사용 가능합니다.</font>\");\r\n");
      out.write("																	$(\r\n");
      out.write("																			'#message1')\r\n");
      out.write("																			.show();\r\n");
      out.write("																	use = \"possible\";\r\n");
      out.write("																}\r\n");
      out.write("															}\r\n");
      out.write("														})\r\n");
      out.write("											});//idcheck click \r\n");
      out.write("\r\n");
      out.write("							$('input[name=\"userId\"]').keydown(function() { // 키가 눌렸을 때.\r\n");
      out.write("								//alert(4);\r\n");
      out.write("								$('#message1').css('display', 'none'); // 안보이게해라.\r\n");
      out.write("								isChange = true; // 글자가 바꼈다.\r\n");
      out.write("								use = \"\"; // 새로운 데이터가 들어오면 use는 \"\" 해서 중복체크 먼저하게 만들기.\r\n");
      out.write("							});\r\n");
      out.write("\r\n");
      out.write("							$('input[name=\"userSub\"]')\r\n");
      out.write("									.click(\r\n");
      out.write("											function() {\r\n");
      out.write("\r\n");
      out.write("												if ($('input[name=\"userId\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"아이디를 입력하세요\");\r\n");
      out.write("													$('input[name=\"id\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if (use == \"impossible\") {\r\n");
      out.write("													alert(\"이미 사용중인 아이디입니다.\");\r\n");
      out.write("													return false;\r\n");
      out.write("												} else if (isCheck == false\r\n");
      out.write("														|| isChange == true) {\r\n");
      out.write("													alert(\"중복체크를 확인하세요\");\r\n");
      out.write("													return false;\r\n");
      out.write("												} else if (isBlank == true) {\r\n");
      out.write("													alert(\"아이디를 입력하세요\");\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($('input[name=\"userPw\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("													$('input[name=\"userPw\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												let check = /^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{10,}$/;\r\n");
      out.write("\r\n");
      out.write("												if (!check.test($(\r\n");
      out.write("														'input[name=\"userPw\"]')\r\n");
      out.write("														.val())) {\r\n");
      out.write("													alert(\"비밀번호 형식이 올바르지 않습니다.\");\r\n");
      out.write("													$('input[name=\"userPw\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($(\r\n");
      out.write("														'input[name=\"userRePw\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("													$(\r\n");
      out.write("															'input[name=\"userRePw\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($(\r\n");
      out.write("														'input[name=\"userRePw\"]')\r\n");
      out.write("														.val() != $(\r\n");
      out.write("														'input[name=\"userPw\"]')\r\n");
      out.write("														.val()) {\r\n");
      out.write("													alert(\"비밀번호가 같지 않습니다.\");\r\n");
      out.write("													$(\r\n");
      out.write("															'input[name=\"userRePw\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($('input[name=\"userName\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"이름을 입력하세요\");\r\n");
      out.write("													$('input[name=\"userName\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($('input[name=\"userEmail\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"이메일을 입력하세요\");\r\n");
      out.write("													$('input[name=\"userEmail\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												var regEmail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/;\r\n");
      out.write("\r\n");
      out.write("												if (regEmail\r\n");
      out.write("														.test($(\r\n");
      out.write("																'input[name=\"userEmail\"]')\r\n");
      out.write("																.val()) == false) {\r\n");
      out.write("													alert('이메일 형식이 올바르지 않습니다.');\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($('input[name=\"userPhone\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"휴대폰 번호를 입력하세요\");\r\n");
      out.write("													$('input[name=\"userPhone\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if (isNaN($(\r\n");
      out.write("														'input[name=\"userPhone\"]')\r\n");
      out.write("														.val())) {\r\n");
      out.write("													alert(\"휴대폰 번호는 숫자만 입력 가능합니다.\");\r\n");
      out.write("													$('input[name=\"userPhone\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($('input[name=\"userAdd\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"주소를 입력하세요\");\r\n");
      out.write("													$('input[name=\"userAdd\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($('input[name=\"postcode\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"주소를 입력하세요\");\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("												if ($(\r\n");
      out.write("														'input[name=\"detailaddress\"]')\r\n");
      out.write("														.val().length == 0) {\r\n");
      out.write("													alert(\"상세 주소를 입력하세요\");\r\n");
      out.write("													$(\r\n");
      out.write("															'input[name=\"detailaddress\"]')\r\n");
      out.write("															.focus();\r\n");
      out.write("													return false;\r\n");
      out.write("												}\r\n");
      out.write("\r\n");
      out.write("											})\r\n");
      out.write("\r\n");
      out.write("						});//ready\r\n");
      out.write("		/** 우편번호 찾기 */\r\n");
      out.write("		function execDaumPostcode() {\r\n");
      out.write("			daum.postcode.load(function() {\r\n");
      out.write("				new daum.Postcode({\r\n");
      out.write("					oncomplete : function(data) {\r\n");
      out.write("						// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.\r\n");
      out.write("						$(\"#postcode\").val(data.zonecode);\r\n");
      out.write("						$(\"#address\").val(data.roadAddress);\r\n");
      out.write("					}\r\n");
      out.write("				}).open();\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("hr {\n");
      out.write("	border-bottom: none;\n");
      out.write("	border-left: none;\n");
      out.write("	border-right: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav input { /* 검색어 */\n");
      out.write("	border-color: #565656;\n");
      out.write("	background-image: url(\"");
      out.print(request.getContextPath());
      out.write("/image/search.jpg\");\n");
      out.write("	background-repeat: no-repeat;\n");
      out.write("	background-position: right;\n");
      out.write("	border-radius: 15px;\n");
      out.write("	background-size: 25px;\n");
      out.write("	outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".top ul { /* 로그인 칸*/\n");
      out.write("	list-style-type: none;\n");
      out.write("	/* 좌측 여백 없애기 */\n");
      out.write("	padding-left: 0px;\n");
      out.write("	/* 우측 정렬 하기 */\n");
      out.write("	float: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".top ul li { /* 로그인칸 */\n");
      out.write("	display: inline;\n");
      out.write("	border-left: 1px solid;\n");
      out.write("	padding: 0px 10px 0px 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".top ul li:first-child { /* 로그인버튼 */\n");
      out.write("	border-left: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: #565656; /* #5d5d5d */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".top {\n");
      out.write("	font-size: 12px;\n");
      out.write("	width: 300px;\n");
      out.write("	height: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".newlogin {\n");
      out.write("	color: #72aa37;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body { /* 전체 글꼴 */\n");
      out.write("	font-family: 'Noto Sans KR', sans-serif;\n");
      out.write("	color: #5d5d5d;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bottom {\n");
      out.write("	color: #5d5d5d;\n");
      out.write("}\n");
      out.write("/*====================================  */\n");
      out.write("* {\n");
      out.write("	list-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: #57523E;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#menu {\n");
      out.write("	position: relative;\n");
      out.write("	z-index: 99;\n");
      out.write("	background-color: white;\n");
      out.write("	height: 50px;\n");
      out.write("	text-align: center;\n");
      out.write("	width: 300px;\n");
      out.write("	margin-left: 400px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("[class*=\"main\"] {\n");
      out.write("	background-color: white;\n");
      out.write("	border-radius: 5px 5px 5px 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("[class*=\"main\"] ul {\n");
      out.write("	border-radius: 5px 5px 5px 5px;\n");
      out.write("	border: 1px solid #57523E;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1 {\n");
      out.write("	padding-left: 0px;\n");
      out.write("	height: 100%;\n");
      out.write("	width: 1000px;\n");
      out.write("	margin: 0 auto;\n");
      out.write("	display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1>li {\n");
      out.write("	float: left;\n");
      out.write("	width: 13%;\n");
      out.write("	line-height: 50px;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1>li:hover .main2 {\n");
      out.write("	left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1>li a {\n");
      out.write("	display: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1>li a:hover {\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main2 {\n");
      out.write("	text-align: left;\n");
      out.write("	width: 170%;\n");
      out.write("	position: absolute;\n");
      out.write("	top: 50px;\n");
      out.write("	left: -9999px;\n");
      out.write("	padding: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1>li:hover {\n");
      out.write("	border-bottom: 3px solid #8ca86e;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main1>li:hover:last-child {\n");
      out.write("	border-bottom: white; /* 장바구니 밑에 색없애기위해. */\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main2 li:hover {\n");
      out.write("	border-left: 4px solid #8ca86e;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main2>li {\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main2>li:hover .main3 {\n");
      out.write("	left: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main2>li a, .main3>li a {\n");
      out.write("	border-radius: 10px;\n");
      out.write("	margin: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main3 {\n");
      out.write("	position: absolute;\n");
      out.write("	top: -10px;\n");
      out.write("	width: 100%;\n");
      out.write("	left: -9999px;\n");
      out.write("	padding: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main3>li a:hover {\n");
      out.write("	color: #5d5d5d;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav {\n");
      out.write("	margin-top: 20px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("	src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.js\"></script>\n");
      out.write("<script>\n");
      out.write("	function ClickCartList(){\n");
      out.write("		var id ='");
      out.print((String) session.getAttribute("id"));
      out.write("';\n");
      out.write("		if(id==\"null\"){\n");
      out.write("			if(confirm(\"로그인이 필요한 페이지 입니다.\\n 로그인 하시겠습니까?\")){\n");
      out.write("				location.href=\"");
      out.print(request.getContextPath());
      out.write("\" + \"/login.jsp\";\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("			   location.href=\"");
      out.print(request.getContextPath());
      out.write("\n");
      out.write("	\" + \"/main.jsp\";\n");
      out.write("		}\n");
      out.write("\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<!-- notosans 폰트 적용 -->\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<body>\n");
      out.write("	");

	/*id 에 해당하는 이름 가져오기  */
	//String id =(String)session.getAttribute("id");
	String id = "dbsgmlwo78";

	UserDAO udaoDao = UserDAO.getinstance();
	User user = udaoDao.getUserById(id);
	System.out.println(user);
	
      out.write("\n");
      out.write("\n");
      out.write("	<form>\n");
      out.write("		<input type=\"hidden\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("	</form>\n");
      out.write("	<div class=\"top\" align=\"right\">\n");
      out.write("		<ul>\n");
      out.write("			");

			if (id != null) {
			
      out.write("\n");
      out.write("			<li><a class=\"newlogin\"\n");
      out.write("				href=\"");
      out.print(request.getContextPath());
      out.write("/mypage.jsp?id=");
      out.print(user.getUserId());
      out.write("\"><font\n");
      out.write("					color=\"#8ca86e\">");
      out.print(user.getUserName());
      out.write("님</font> <font\n");
      out.write("					color=\"#5d5d5d\">마이페이지</font></a></li>\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/logout.jsp\">로그아웃</a></li>\n");
      out.write("\n");
      out.write("			");

			} else {
			
      out.write("\n");
      out.write("			<li><a class=\"newlogin\"\n");
      out.write("				href=\"");
      out.print(request.getContextPath());
      out.write("/register.jsp\">회원가입</a></li>\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/login.jsp\">로그인</a></li>\n");
      out.write("			");

			}
			
      out.write("\n");
      out.write("			<li><a href=\"");
      out.print(request.getContextPath());
      out.write("'여기에 고객센터 넣어주세요.jsps'\">고객센터</a></li>\n");
      out.write("		</ul>\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- 로고  -->\n");
      out.write("\n");
      out.write("	<div align=\"center\" class=\"logo\">\n");
      out.write("		<a href=\"");
      out.print(request.getContextPath());
      out.write("/main.jsp\"><img\n");
      out.write("			src=\"");
      out.print(request.getContextPath());
      out.write("/image/mama.png\" width=400\n");
      out.write("			height=150></a>\n");
      out.write("	</div>\n");
      out.write("	<br>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!--상단 메뉴바  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- 일반 사용자일때 메뉴바 -->\n");
      out.write("	<div id=\"menu\">\n");
      out.write("		<ul class=\"main1\">\n");
      out.write("			<li style=\"border: none;\"><a href=\"#\"><b\n");
      out.write("					style=\"font-size: 20px;\"><span style=\"font-size: 20px;\">≡</span>\n");
      out.write("						카테고리</b></a>\n");
      out.write("				<ul class=\"main2\">\n");
      out.write("\n");
      out.write("					");

					//         CategoryDao cdao = CategoryDao.getinstance();
					//       	CategoryDao2 cdao2 = CategoryDao2.getinstance();

					//       	ArrayList<CategoryBean>lists = cdao.getAllCategory(); 
					//       	ArrayList<CategoryBean2>list = null;

					//       	System.out.println("CategoryBean list:"+lists.size());
					// 		System.out.println("CategoryBean2 list:"+lists.size());
					//         for(CategoryBean cb : lists){
					
      out.write("\n");
      out.write("					");
      out.write("\n");
      out.write("<!-- 					<ul class=\"main3\"> -->\n");
      out.write("\n");
      out.write("// 						list = cdao2.getAllCategory(cb.getCode1());\n");
      out.write("// 						for (CategoryBean2 cb2 : list) {\n");
      out.write("\n");
      out.write("<!-- 						<li><a -->\n");
      out.write('\n');
      out.write("\n");
      out.write("// 						// }//CategoryBean2\n");
      out.write("\n");
      out.write("<!-- 					</ul></li> -->\n");
      out.write("			");

// 			} //CategoryBean
			
      out.write("\n");
      out.write("		</ul>\n");
      out.write("		</li>\n");
      out.write("		");

		String[] menubar = { "BEST", "신상품", "알뜰상품", "기획상품" };
		for (int i = 0; i < menubar.length; i++) {
		
      out.write("\n");
      out.write("		<li><a\n");
      out.write("			href=\"");
      out.print(request.getContextPath());
      out.write("/mainmenu.jsp?pspec=");
      out.print(menubar[i]);
      out.write('"');
      out.write('>');
      out.print(menubar[i]);
      out.write("</a></li>\n");
      out.write("		");

		}
		
      out.write("\n");
      out.write("		<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/coupon.jsp\">특가 /\n");
      out.write("				혜택</a></li>\n");
      out.write("		<li style=\"margin-left: 50px; padding-bottom: 0;\"><a\n");
      out.write("			href=\"javascript:ClickCartList()\"><img width=\"35px\" height=\"35px\"\n");
      out.write("				src=\"");
      out.print(request.getContextPath());
      out.write("/image/cart.png\"></a></li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<hr width=80% class=\"categoryhr\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<br> <br>\r\n");
      out.write("		<h2>회원가입</h2>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form name=\"f\" action=\"registerAction.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"essencial\">\r\n");
      out.write("				<font style=\"color: orange;\">*</font>필수입력사항\r\n");
      out.write("			</div>\r\n");
      out.write("			<hr color=\"#5d5d5d\" width=40% class=\"newloginhr\">\r\n");
      out.write("			<table width=37% class=\"newlogintable\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><b>아이디</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\"><input class=\"idch\" maxlength=\"15\"\r\n");
      out.write("						height=20px type=\"text\" id=\"text\" name=\"userId\"\r\n");
      out.write("						placeholder=\"  최대 15자 입력 가능합니다.\"></td>\r\n");
      out.write("					<td align=\"center\"><input type=\"button\" id=\"button\"\r\n");
      out.write("						name=\"userIdCheck\" value=\"중복확인\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr height=30>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td><span id=\"message1\"></span></td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><b>비밀번호</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\"><input type=\"password\" id=\"text\"\r\n");
      out.write("						name=\"userPw\" placeholder=\"  비밀번호를 입력해주세요\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td style=\"display: none;\" class=\"pwmsg\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<font size=2px>\r\n");
      out.write("								<li>8자 이상 입력</li>\r\n");
      out.write("								<li>영문/숫자/특수문자(공백 제외)만 허용하며, 2개 이상 조합</li>\r\n");
      out.write("							</font>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td width=\"150px\"><b>비밀번호확인</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\"><input type=\"password\" id=\"text\"\r\n");
      out.write("						name=\"userRePw\" placeholder=\"  비밀번호를 입력해주세요\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td></td>\r\n");
      out.write("					<td style=\"display: none;\" class=\"repwmsg\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<font size=2px>\r\n");
      out.write("								<li>동일한 비밀번호를 입력해주세요.</li>\r\n");
      out.write("							</font>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><b>이름</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\"><input type=\"text\" id=\"text\"\r\n");
      out.write("						name=\"userName\" placeholder=\"  이름을 입력해주세요\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><b>이메일</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\"><input type=\"text\" id=\"text\"\r\n");
      out.write("						name=\"userEmail\" placeholder=\"예 : abcd123@yelmiya.com\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><b>휴대폰</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\"><input maxlength=\"11\" type=\"text\" id=\"text\"\r\n");
      out.write("						name=\"userPhone\" placeholder=\"  숫자만 입력해주세요\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr></tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<!-- 주소칸 -->\r\n");
      out.write("					<td><b>주소</b><span class=\"im\">*</span></td>\r\n");
      out.write("					<td align=\"center\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" name=\"userPostcode\" id=\"postcode\"\r\n");
      out.write("									placeholder=\"  우편번호\" readonly />\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" name=\"userAdd\" id=\"address\"\r\n");
      out.write("									placeholder=\"  주소\" readonly />\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" name=\"userDetailAdd\" id=\"detailaddress\"\r\n");
      out.write("									placeholder=\"  상세주소\" required />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div>\r\n");
      out.write("							<button id=\"button\" type=\"button\" id=\"button\"\r\n");
      out.write("								onclick=\"execDaumPostcode()\">우편번호 찾기</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><b>성별</td>\r\n");
      out.write("					<td align=\"center\"><input type=\"radio\" name=\"userGender\"\r\n");
      out.write("						value=\"남\">남 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <input\r\n");
      out.write("						type=\"radio\" name=\"userGender\" value=\"여\">여</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th align=\"left\">생년월일</th>\r\n");
      out.write("					<td align=\"center\"><input type=\"date\" id=\"text\"\r\n");
      out.write("						name=\"userBirth\" placeholder=\"생년월일을 선택해주세요\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"3\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("						id=\"button\" name=\"userSub\" value=\"회원가입\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\", initial-scale = \"1\">\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("	.bottomtop{\n");
      out.write("		font-size: 15px;\n");
      out.write("	}\n");
      out.write("	.bottombt{\n");
      out.write("		font-size: 12px;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<!-- bottom -->\n");
      out.write("<br>\n");
      out.write("<hr width=80% class=\"categoryhr\">\n");
      out.write("\n");
      out.write("<table  width=80% align=\"center\">\n");
      out.write("	<tr>\n");
      out.write("		<th width=\"30%\" align=\"left\" class=\"bottomtop\">마켓퀄리</th>\n");
      out.write("		<th width=\"30%\" align=\"left\" class=\"bottomtop\">고객센터</th>\n");
      out.write("		<th width=\"30%\" align=\"left\" class=\"bottomtop\">전자금융거래 분쟁처리</th>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td>\n");
      out.write("			<table>\n");
      out.write("				<tr align=\"left\">\n");
      out.write("					<td width=\"80%\" class=\"bottombt\">사업자등록번호 123-456-00000 통신판매업신고번호 0000-신림-0123호\n");
      out.write("						대표이사 윤희재 서울시 95, NAVER 0000, 12345\n");
      out.write("						전화 1588-0000 이메일 dbsgmlwo78@naver.com 사업자등록정보 확인\n");
      out.write("					<td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("		<td>\n");
      out.write("			<table>\n");
      out.write("				<tr align=\"left\">\n");
      out.write("					<td width=\"80%\" class=\"bottombt\">\n");
      out.write("					서울시 관악구 신림동 윤희재다\n");
      out.write("					전화 1588-0000\n");
      out.write("					결제도용신고 1588-0000\n");
      out.write("					<td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("		<td>\n");
      out.write("			<table>\n");
      out.write("				<tr align=\"left\">\n");
      out.write("					<td width=\"80%\" class=\"bottombt\">\n");
      out.write("					전화 1589-0000\n");
      out.write("					<td>\n");
      out.write("				</tr>\n");
      out.write("			</table>\n");
      out.write("		</td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
